- name: Archive project
  run: tar -czvf app.tar.gz .

- name: Copy archive to EC2
  uses: appleboy/scp-action@v0.1.4
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    source: "app.tar.gz"
    target: "/home/ubuntu/"
