name: Testing & Deploy Django App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # Step 3: Install dependencies for local testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Django tests locally
      - name: Run Tests
        run: |
          python manage.py test

      # Step 5: Archive project as tar.gz
      - name: Archive project
        run: |
          tar --warning=no-file-changed -czf app.tar.gz --exclude='.git' --exclude='.github' . || echo "Tar completed with warnings"

      # Step 6: Copy archive to EC2 instance
      - name: Copy archive to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "app.tar.gz"
          target: "/home/ubuntu/"

      # Step 7: SSH into EC2 and deploy
      - name: Deploy to AWS EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/ubuntu/app_test
            tar -xzvf /home/ubuntu/app.tar.gz -C /home/ubuntu/app_test
            cd /home/ubuntu/app_test
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn || echo "Gunicorn restart skipped"
